<a href="https://colab.research.google.com/github/liondhindsa666-svg/RETAIL-SALES-ANALYSIS-DASHBOARD/blob/main/Project_1_Manual_CLeaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
fun=pd.read_csv('/startup_funding.csv')
np.random.seed(0)

In [5]:
fun.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Unnamed: 9
0,1,09-01-2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13-01-2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09-01-2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02-01-2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02-01-2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [6]:
fun.isnull()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Unnamed: 9
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
3039,False,False,False,True,True,True,False,False,False,True
3040,False,False,False,True,True,True,False,False,False,False
3041,False,False,False,True,True,True,False,False,False,True
3042,False,False,False,True,True,True,False,False,True,False
3043,False,False,False,True,True,True,False,False,False,True

In [7]:
missing=fun.isnull().sum()
missing

Sr No                   0
Date dd/mm/yyyy         0
Startup Name            0
Industry Vertical     171
SubVertical           936
City  Location        180
Investors Name         24
InvestmentnType         4
Amount in USD         960
Unnamed: 9           2625
dtype: int64

In [8]:
total_cells=np.prod(fun.shape)
total_missing=missing.sum()
percent_missing=(total_missing/total_cells)*100
print(percent_missing)

16.09724047306176

In [9]:
fun.drop('Unnamed: 9',axis=1,inplace=True)

In [10]:
fun =fun.rename(columns={
    'Date dd/mm/yyyy':'Date',
    'City  Location':'City',
    'InvestmentnType':'Investment_Type',
    'Amount in USD':'Amount_USD'
    })

In [11]:
fun.fillna(0)

,Sr No,Date,Startup Name,Industry Vertical,SubVertical,City,Investors Name,Investment_Type,Amount_USD
0,1,09-01-2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,13-01-2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,09-01-2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,02-01-2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,02-01-2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"
...,...,...,...,...,...,...,...,...,...
3039,3040,29-01-2015,Printvenue,0,0,0,Asia Pacific Internet Group,Private Equity,"45,00,000"
3040,3041,29-01-2015,Graphene,0,0,0,KARSEMVEN Fund,Private Equity,"8,25,000"
3041,3042,30-01-2015,Mad Street Den,0,0,0,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000"
3042,3043,30-01-2015,Simplotel,0,0,0,MakeMyTrip,Private Equity,0
3043,3044,31-01-2015,couponmachine.in,0,0,0,UK based Group of Angel Investors,Seed Funding,"1,40,000"

In [12]:
fun['Date']=pd.to_datetime(fun['Date'],errors='coerce')

In [13]:
fun

,Sr No,Date,Startup Name,Industry Vertical,SubVertical,City,Investors Name,Investment_Type,Amount_USD
0,1,2020-09-01,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
1,2,NaT,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
2,3,2020-09-01,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
3,4,2020-02-01,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
4,5,2020-02-01,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"
...,...,...,...,...,...,...,...,...,...
3039,3040,NaT,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000"
3040,3041,NaT,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000"
3041,3042,NaT,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000"
3042,3043,NaT,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN
3043,3044,NaT,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000"

In [14]:
print(fun['Amount_USD'].dtype)

object

In [15]:
fun['Amount_USD'] = (
    fun['Amount_USD']
    .astype(str)
    .str.replace(',', '', regex=False)
)

fun['Amount_USD'] = pd.to_numeric(fun['Amount_USD'], errors='coerce')

In [16]:
print(fun['Amount_USD'].dtype)

float64

In [17]:
# Industry Vertical
fun['Industry Vertical'].fillna('Unknown', inplace=True)

# SubVertical
fun['SubVertical'].fillna('Not Specified', inplace=True)

# City
fun['City'].fillna('Unknown', inplace=True)

# Investors Name
fun['Investors Name'].fillna('Undisclosed', inplace=True)

/tmp/ipykernel_3214/3481865148.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fun['Industry Vertical'].fillna('Unknown', inplace=True)
/tmp/ipykernel_3214/3481865148.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fun['SubVertical'].fillna('Not Specified', inplace=True)
/tmp/ipykernel_3214/3481865148.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fun['City'].fillna('Unknown', inplace=True)
/tmp/ipykernel_3214/3481865148.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fun['Investors Name'].fillna('Undisclosed', inplace=True)

In [18]:
fun

,Sr No,Date,Startup Name,Industry Vertical,SubVertical,City,Investors Name,Investment_Type,Amount_USD
0,1,2020-09-01,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0
1,2,NaT,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0
2,3,2020-09-01,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0
3,4,2020-02-01,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0
4,5,2020-02-01,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0
...,...,...,...,...,...,...,...,...,...
3039,3040,NaT,Printvenue,Unknown,Not Specified,Unknown,Asia Pacific Internet Group,Private Equity,4500000.0
3040,3041,NaT,Graphene,Unknown,Not Specified,Unknown,KARSEMVEN Fund,Private Equity,825000.0
3041,3042,NaT,Mad Street Den,Unknown,Not Specified,Unknown,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000.0
3042,3043,NaT,Simplotel,Unknown,Not Specified,Unknown,MakeMyTrip,Private Equity,NaN
3043,3044,NaT,couponmachine.in,Unknown,Not Specified,Unknown,UK based Group of Angel Investors,Seed Funding,140000.0

In [19]:
fun['Investment_Type'].value_counts()

Investment_Type
Private Equity                 1356
Seed Funding                   1355
Seed/ Angel Funding              60
Seed / Angel Funding             47
Seed\\nFunding                   30
Debt Funding                     25
Series A                         24
Seed/Angel Funding               23
Series B                         20
Series C                         14
Series D                         12
Angel / Seed Funding              8
Seed Round                        7
Seed                              4
Private Equity Round              4
Pre-Series A                      4
Seed / Angle Funding              3
Equity                            2
Series E                          2
Corporate Round                   2
Venture Round                     2
Series F                          2
pre-Series A                      2
Seed Funding Round                1
Single Venture                    1
Maiden Round                      1
pre-series A                      1
Funding Round                     1
Series G                          1
Series H                          1
Venture                           1
Pre-series A                      1
Debt and Preference capital       1
Debt                              1
Bridge Round                      1
Angel Round                       1
Venture - Series Unknown          1
Series J                          1
Angel                             1
Series B (Extension)              1
Mezzanine                         1
Debt-Funding                      1
Pre Series A                      1
Inhouse Funding                   1
Equity Based Funding              1
Seed funding                      1
Private Funding                   1
Private                           1
Structured Debt                   1
PrivateEquity                     1
Term Loan                         1
Angel Funding                     1
Private\\nEquity                  1
Crowd funding                     1
Crowd Funding                     1
Name: count, dtype: int64

In [20]:
fun['Investment_Type'] = fun['Investment_Type'].str.strip()

In [27]:
fun['Investment_Type'] = fun['Investment_Type'].replace({
    'Seed/ Angel Funding': 'Seed Funding',
    'Seed / Angel Funding': 'Seed Funding',
    'Seed/Angel Funding': 'Seed Funding',
    'Seed / Angle Funding': 'Seed Funding',
    'Seed\\nFunding': 'Seed Funding',
    'Angel / Seed Funding': 'Seed Funding',
    'Seed Round': 'Seed Funding',
})

In [28]:
fun['Investment_Type'].value_counts()

Investment_Type
Seed Funding                   1503
Private Equity                 1356
Seed\\nFunding                   30
Debt Funding                     25
Series A                         24
Series B                         20
Series C                         14
Series D                         12
Private Equity Round              4
Seed                              4
Pre-Series A                      4
Corporate Round                   2
Equity                            2
pre-Series A                      2
Series E                          2
Venture Round                     2
Series F                          2
Maiden Round                      1
Funding Round                     1
Venture                           1
Series H                          1
Series G                          1
Pre-series A                      1
Single Venture                    1
Angel                             1
Angel Round                       1
Series J                          1
Venture - Series Unknown          1
Bridge Round                      1
Debt and Preference capital       1
Inhouse Funding                   1
Seed Funding Round                1
pre-series A                      1
Pre Series A                      1
Debt                              1
Mezzanine                         1
Debt-Funding                      1
Equity Based Funding              1
Private Funding                   1
Seed funding                      1
Series B (Extension)              1
Private                           1
Structured Debt                   1
PrivateEquity                     1
Term Loan                         1
Angel Funding                     1
Private\\nEquity                  1
Crowd funding                     1
Crowd Funding                     1
Name: count, dtype: int64

In [29]:
print(fun.duplicated().sum())

0

In [30]:
fun['Startup Name'] = fun['Startup Name'].str.strip()

In [31]:
fun['Startup Name'].value_counts()

Startup Name
Swiggy             8
Ola Cabs           8
Paytm              7
Medinfi            6
NoBroker           6
                  ..
Hostel Dunia       1
Play your sport    1
Dhruva Space       1
Ecozen             1
Pando              1
Name: count, Length: 2459, dtype: int64

In [32]:
fun['Funding_Category'] = pd.cut(
    fun['Amount_USD'],
    bins=[0,1000000,10000000,50000000,1000000000],
    labels=['Small','Medium','Large','Mega']
)

In [33]:
print(fun['Funding_Category'].value_counts())

Funding_Category
Small     916
Medium    721
Large     310
Mega      114
Name: count, dtype: int64

In [34]:
fun.to_csv('startup_funding_cleaned.csv', index=False)